### ISSUE TITLE
Running on Heroku

### ISSUE THREAD

**Issue by npateman** [martylouis/grav-heroku#1]
Hi there,

As the title suggests, you are running this on Heroku?  I was wondering if you could maybe let me know what things need changing from the base install in order to deploy to Heroku?  At the moment i'm using the RTFM skeleton and Heroku is running through the deploy process fine, but then just giving me 500 errors.

I was pointed toward the .htaccess file which I have made identical to yours, but still no joy.

Many thanks in advance.

**Comment by martylouis** [comment]
Hey @npateman,

I haven't been able to get back around to this. Was sorta waiting to see if Grav would come with something. Sorry can't me much more help, maybe this can be more help » https://github.com/akhyarrh/grav-test

Thanks

**Comment by npateman** [comment]
Okay I found the issue, the following needed to be included in composer.json require section,

```
"ext-mbstring": "*",
```
